# Generated by Django 5.0.6 on 2024-06-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
